---
title: "Maternite"
author: "JcB"
date: "17/08/2014"
output: word_document
---

source:

- package __epi__
- Gebolini Christophe: [Lire, compter, tester... avec R](http://cran.r-project.org/doc/contrib/Genolini-LireCompterTesterR.pdf)

Plan
====

- Présentation de la structure d'un article médical
- Statistique: méthode scientifique pour rendre les données compréhensibles afin de tirer des conclusions pertinentes (ex du cholera avec john snow). Quatre étapes
        - statistique descriptive
        - statistique inférentielle
        - modélisation
- domaines connexes: astronomie (Neptune), Big Data, sondages d'opinion, démographie, épidémiologie, cartographie, pharmacologie...
- les données: matière première du statisticien
- cas clinique: Births
        - description des variables
        - paramètres de position et de dispersion: moyenne, variance, écart-type, médiane
        - représentation graphique
        - corrélation
        - comparaison de deux groupes: les tests  d'hypothèse
        - ANOVA

births Births in a London Hospital
==================================

Description
-----------
Données provenant de 500 naissances uniques (singleton births) dans un hôpital de Londres.

Origine: données __Births__ du pacfage __epi__.

Usage

data(births)

Format (Métadonnées)
------
Un tableau (data frame) de 500 observations concernant les 8 variables suivantes:


variable  |  signification   
----------|---------------  
__id__  |  Identifiant pour la mère et l'enfant   
__bweight__  |  Poids de naissance
__lowbw__ | Poids inférieur à 2500 g (0 = non, 1 = oui)
__gestwks__| Durée de la grossesse (semaines)
__preterm__| Durée de gestation inférieure à 37 weeks (0 = non, 1 = oui)
__matage__| Age maternel
__hyp__| Hypertension gravidique (0 = non, 1 = oui)
__sex__| Sexe de l'enfant 1:garçon, 2:fille

Source
-------
Anonymous

References
Michael Hills and Bianca De Stavola (2002). A Short Introduction to Stata 8 for Biostatistics,[Timberlake Consultants Ltd](http://www.timberlake.co.uk)

[A short introduction to R for Epidemiology](http://bendixcarstensen.com/Epi/R-intro-SDC.pdf) page 6, paragraphe 2.5

Exploration des données
-----------------------

```{r births,echo=FALSE,comment=""}
library("Epi")
data(births)
head(births)
str(births)
births$sex <- as.factor(births$sex)
births$hyp <- as.factor(births$hyp)
births$preterm <- as.factor(births$preterm)
births$lowbw <- as.factor(births$lowbw)
summary(births)

summary(births[births$preterm==0,])
summary(births[births$preterm==1,])
premature <- births[births$preterm==1,]
aterme <- births[births$preterm==0,]
hist(premature$bweight)
hist(aterme$bweight)

# age maternel
summary(births$matage)

attach(births)

hist(births$matage, main = "Histogramme de l'age maternel", ylab="nombre", xlab="Age (années)", col="gray", border="white")
mean_matage <- mean(births$matage)
sd_matage <- sd(births$matage)
x <- seq(23, 43, 0.1)
lines(x, dnorm(x, mean(matage), sd(matage)) * 1000, type = "l", col="blue")


w <- seq(500, 5000, le=100)
plot(w, dnorm(w,mean(aterme$bweight, na.rm=T),sd(aterme$bweight, na.rm=T)), xlim = c(500, 5000), type = "l")
lines(w, dnorm(w,mean(premature$bweight, na.rm=T),sd(premature$bweight, na.rm=T)), xlim = c(500, 5000))

```



